#+STARTUP: showall hidestars indent
#+BEGIN_HTML
---
layout: post
title:  Trans people should not be allowed to pee!
snip:   Get all those trans/homo/bisexual people outta our public bathrooms!
---
#+END_HTML


Let's face it, trans people should not be allowed to use public
bathrooms for straight, cisgendered people. Trans people are
weird. Like, *really* weird. And they do make normal, straight people
immensely uncomfortable. As such, I am forced to agree with John
Kavanagh, and reinforce his claim that [[https://www.allout.org/en/actions/arizona][If you think someone is using a
public bathroom that's the wrong gender for them, THEY SHOULD FACE THE
JAIL!]]

Now, unlike John, I hold a more extremist view on this subject. Why stop
at trans people? There are lots of other things that make normal,
straight people likewise uncomfortable. For example, this scenario:

#+BEGIN_QUOTE
  You're a white, christian, straight man, making your way over to the
  public bathroom in a STEM convention. You decide to use the urinals,
  like any sane person would in this occasion. At this point, another
  man (if we ever could call that... *disgusting thing* that), looks at
  you and stops at the urinal at your side. He pulls out his dick, still
  staring at you, making faces at you. HOLY MOTHER OF FUCKS HE'S MAKING
  FACES AT YOU! You feel violated, wishing all this awkward moment will
  end as soon as possible. You feel an urge to punch him, but decide not
  to: that would cause a huge commotion, and what if people think *you*
  are gay too?! Oh, God forbid that!
#+END_QUOTE

There's no denying that this sort of thing should not happen to normal,
white, straight men. Life is already way too difficult as it is. And
these things, these feelings of being violated! Oh my dearest God, I can
not even think about these! As such, I propose we don't stop with just
potentially forbidding trans people from using public bathrooms, but
also homosexuals. Those disgusting, vile people!

However, by taking such actions, the international community and the
"human" rights community might be upset at America[fn:1]. People might
say we are not "inclusive" for people. Or that we're not a truly "free"
country. Or even utter bullshit like "We're not making progress, but
regressing instead!" Those fools! The 19th century was clearly more
developed in manners and society values as this century. We truly valued
masculinity back then. And now? Now we have these... oh I can't even
finish this phrase. It disgusts me so.

None the less, we want the Americans who might support this kind of
things to think we're being "inclusive", so I propose that besides
forbidding those weird fucks to use public bathrooms, we should do so
under the pretence of "We want to make Americans not feel violated when
using a public place.". This would mean that the rules for using public
bathrooms would have to change to the following:

 - Public bathroom usage would be defined by gender *and*
   sexual/romantic orientation. That is, you would only be able to use
   the public bathroom that fits your gender (with a distinction on
   cis/trans people), and your sexual orientation.
   
   So, /homosexual cis-men/ would have to use a separate bathroom than
   an /heterosexual cis-men/, which is only reasonable. A /homosexual
   trans-men/ would not use the same public bathroom as a /homosexual
   cis-men/, even more if that trans people haven't fully completed the
   procedures for sex reassignment yet.

   For /genderfluid/ people, this mean we'd need an additional division,
   since those fuckers might feel like a man one day and a woman the
   other day. Disgusting!


 - Public places, if providing public bathrooms, would be *required by
   law* to provide bathrooms for every combination of gender and
   sexual/romantic orientations. Since we don't have a fixed number of
   these, this could potentially grow to infinity.

   This would, of course, need to have a flaw in the law's writing such
   that a decent lawyer could use it to say "Oh, we're still trying to
   adapt to the changes, just give us a little more time." Of course, as
   long as the place has public bathrooms for /straight cis-men/ and
   /straight cis-women/. If the place doesn't provide these, we should
   just fuck them up.


 - People who are reported as using the wrong public bathroom for their
   gender or sexual/orientation will face a penalty according to how
   weird they are. Thus, /straight cis/ people would just have to spend
   the night on the jail. Weird people would spend a lot more.



* Conclusion

I really think this is the way America should go. To deny that people
who don't conform with the gender roles for their biological sex are
even people. This is a huge improvement from the 19th century, and I
believe perhaps even more than the Dark Age. It's likely to also be more
inclusive than the Nazi Germany, if we keep at it with all our
strength.

[[https://www.allout.org/en/actions/arizona][Let's together make America a better place for /straight, white,
cis-men/, who are already way too bullied by their social position, and
worse, threatened by this scourge of weird asses who insist in labelling
themselves "human".]]


* About this piece

I'm a genderfluid, asexual, panromantic person who was just way too
shocked with mister John Kavanagh's proposed law. If you don't get it,
this blog post is riddled with blatant sarcasm, and I'm just expressing
my support to the petition linked a few times throughout this post
(https://www.allout.org/en/actions/arizona), by showing how absurd this
law really is :3


[fn:1]: I don't even know why it's called human rights, they defend the
        rights of gay and trans people, who clearly are not human.
